feat: display virtual field "current rate"
alyf-de/simple_subscription pull request #5
Opened 2024-09-12 16:48 UTC by HenningWendtland

2024-09-14 14:31 UTC, barredterra requested changes

2024-09-14 14:31 UTC, barredterra commented on simple_subscription/simple_subscription/doctype/simple_subscription_item/simple_subscription_item.py
> +		return item.description
```suggestion
		return frappe.db.get_value("Item", self.item, "description")
```

2024-09-14 14:31 UTC, barredterra commented on simple_subscription/simple_subscription/doctype/simple_subscription_item/simple_subscription_item.py
> +		return item.item_name
```suggestion
		return frappe.db.get_value("Item", self.item, "item_name")
```

2024-09-14 14:31 UTC, barredterra commented on simple_subscription/simple_subscription/doctype/simple_subscription_item/simple_subscription_item.py
> +		return item_details.price_list_rate - (item_details.discount_amount or 0)
```suggestion
		parent = frappe.get_doc("Simple Subscription", self.parent)
		currency = parent.currency or frappe.get_cached_value(
			"Company", parent.company, "default_currency"
		)

		party_details = get_party_details(
			party=parent.customer,
			account=None,
			party_type="Customer",
			company=parent.company,
			posting_date=today(),
			currency=currency,
			doctype="Sales Invoice",
			fetch_payment_terms_template=False,
		)

		price_list = party_details.selling_price_list or frappe.db.get_value(
			"Price List", {"selling": 1, "currency": currency, "enabled": 1}
		)

		item_details = get_item_details(
			{
				"item_code": self.item,
				"company": parent.company,
				"doctype": "Sales Invoice",
				"currency": currency,
				"price_list_currency": currency,
				"qty": self.qty,
				"plc_conversion_rate": 1,
				"conversion_rate": 1,
				"customer": parent.customer,
				"transaction_date": today(),
				"price_list": price_list,
			}
		)
		return item_details.price_list_rate - (item_details.discount_amount or 0)
```

We need to fetch the default currency, if the current subscription doesn't have one yet. And the default price list, if there's no specific one for the customer.

2024-10-14 09:35 UTC, HenningWendtland commented
@barredterra 
Can this be merged?

2024-10-14 15:29 UTC, barredterra approved these changes

2024-10-14 15:30 UTC, merged